config/routes.rb
Mktdemo::Application.routes.draw do
  

  devise_for :users

  resources :users, only: [:update, :edit]

  get '/seller/:id/profile' => "users#sellerp", as: :sellerp
  put '/seller/:id' => "users#sellerprofile", as: :sellerprofile

  resources :listings do
        collection do
          post 'import'
          get 'search'
          get 'ownsearch'
          get 'delete_all'
        end
   resources :orders, only: [:new, :create, :update, :show]
  end
 
  match "/swh", :to => "orders#swh", :as => :swh, :via => :post

  get '/listings/s/:id' => 'listings#vendor', as: 'vendor'
  get '/listings/c/:category' => 'listings#category', as: 'category'
  get '/listings/p/sale' => 'listings#sale', as:'sale'

  get "pages/about"
  get "pages/contact"
  get "pages/terms_conditions"
  get "pages/privacy_policy"
  get "pages/blogger_partnerships"
  get "pages/sell"
  get "pages/sellerfaqs"
  get "pages/csvimport"
  get "pages/returns"
  get "pages/feedback"
  get "pages/testpic"

  get 'seller' => "listings#seller"
  get 'check_listing_status' => "listings#check_listing_status"
  get 'sales' => "orders#sales"
  get 'shipconf' => "orders#shipconf"
  get 'purchases' => "orders#purchases"
  get 'thankyou' => "orders#thankyou"
  get 'admin' => "listings#admin"
  

  root 'listings#index'

  

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json

  def index
      if params[:sort] == "- Price - Low to High"
        @listings = Listing.not_expired.order("price ASC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Price - High to Low"
        @listings = Listing.not_expired.order("price DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- New Arrivals"
        @listings = Listing.not_expired.order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Random Shuffle"
        @listings = Listing.not_expired.order("random()").paginate(:page => params[:page], :per_page => 48)
      else
        @listings = Listing.not_expired.order("random()").paginate(:page => params[:page], :per_page => 48)
      end

       respond_to do |format|
         format.html
         format.csv { send_data @listings.to_csv(@listings) }   
       end

      # @listings = Listing.not_expired.order("created_at DESC").paginate(:page => params[:page], :per_page => 48)  
      # respond_to do |format|
      #    format.html
      #    format.csv { send_data @listings.to_csv(@listings) }   
      #  end
        
  end

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC") #.paginate(:page => params[:page], :per_page => 48)
     respond_to do |format|
         format.html
         format.csv { send_data @listings.to_csv(@listings) }  
      end
  end

  def category
    @category = params[:category]
    #@listings = Listing.not_expired.where(:category => @category).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)

      if params[:sort] == "- Price - Low to High"
        @listings = Listing.not_expired.where(:category => @category).order("price ASC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Price - High to Low"
        @listings = Listing.not_expired.where(:category => @category).order("price DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- New Arrivals"
        @listings = Listing.not_expired.where(:category => @category).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Random Shuffle"
        @listings = Listing.not_expired.where(:category => @category).order("random()").paginate(:page => params[:page], :per_page => 48)
      else
        @listings = Listing.not_expired.where(:category => @category).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      end

  end

   def sale
      if params[:sort] == "- Price - Low to High"
        @listings = Listing.not_expired.where("saleprice > ?", 0).order("price ASC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Price - High to Low"
        @listings = Listing.not_expired.where("saleprice > ?", 0).order("price DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- New Arrivals"
        @listings = Listing.not_expired.where("saleprice > ?", 0).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Random Shuffle"
        @listings = Listing.not_expired.where("saleprice > ?", 0).order("random()").paginate(:page => params[:page], :per_page => 48)
      else
        @listings = Listing.not_expired.where("saleprice > ?", 0).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      end
  end

  def admin
     if current_user.name == "admin admin"
        @listings = Listing.not_expired.order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
     else
        redirect_to root_url, notice: "Sorry, you are not authorized to view the admin page."
     end
  end

  def vendor
    @user = User.find(params[:id])
    #@listings = Listing.not_expired.where(user: User.find(params[:id])).paginate(:page => params[:page], :per_page => 48)

      if params[:sort] == "- Price - Low to High"
        @listings = Listing.not_expired.where(user: User.find(params[:id])).order("price ASC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Price - High to Low"
        @listings = Listing.not_expired.where(user: User.find(params[:id])).order("price DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- New Arrivals"
        @listings = Listing.not_expired.where(user: User.find(params[:id])).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      elsif params[:sort] == "- Random Shuffle"
        @listings = Listing.not_expired.where(user: User.find(params[:id])).order("random()").paginate(:page => params[:page], :per_page => 48)
      else
        @listings = Listing.not_expired.where(user: User.find(params[:id])).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
      end

  end

  def search
    if params[:search].present?

      @listings = Listing.search(params[:search], where: { inventory: {gt: 0},
                                           or: [
                                                 [{updated_at: {gte: (Date.current - 30.day)}}, {user_id: 24}]
                                               ] })

     # @listings = Listing.search(params[:search], where: { inventory: {gt: 0} })
     else
      @listings = Listing.order("created_at DESC")
    end
  end

  def ownsearch
    if params[:search].present?
      @listings = Listing.where(user: current_user).ownsearch(params[:search])
     else
      @listings = Listing.where(user: current_user).order("created_at DESC")
    end
  end

  def show
    if request.path != listing_path(@listing)
      redirect_to @listing, status: :moved_permanently
    end
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id    

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end

   ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)

  end

  def check_listing_status
    user_listing = UserListing.find_by(user:current_user)
    render :json => -1 if user_listing.nil?
    unless user_listing.nil?
      @process_status = user_listing.process_status + 1
      render :json => @process_status - 1

      user_listing.listed! if user_listing.is_processed? or user_listing.is_failed?
   end



  end

 require 'fileutils'

  def import
    tmp = params[:my_file].tempfile

    #FSOTO: I created a new model that has your csv as a attachment and are related to your current_user
    userListing = UserListing.find_by(user:current_user)

    if (userListing.nil?)
      userListing = UserListing.create(file: tmp, user: current_user)
    else
      userListing.file = tmp
    end

    userListing.ready!

    #FSOTO: Now userListng.file.url has a valid file on S3, that can be access from your job.
    Listing.import(userListing.file.url , params[:user_id])
    redirect_to seller_url
  end

  def update
    @listing.slug = nil
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end

    ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)

  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to seller_url, notice: 'Listing was successfully deleted.' }
      format.json { head :no_content }
  end

   ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)

  end

  def delete_all
    Listing.where(user: current_user).delete_all
    flash[:notice] = "You have deleted all your listings."
    redirect_to seller_path

    ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :made_to_order, :designer_or_brand, :description, :price, :saleprice, :inventory, :category,
                                      :sku, :image, :image2, :image3, :image4, :featured, :delete_image2, :delete_image3, :delete_image4)
    end

    def check_user
      if current_user.id != @listing.user_id && current_user.name != "admin admin"
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

end


   

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_designers.html.erb
<h4>Discover new designers & brands...</h4>

<div class="center">
  <div class="row">
    <% User.select('users.*, RANDOM()').where("profileimage_file_name != ? AND profilestory != ? and hidelistings = ?", "", "", "f").
                joins(:listings).
                where('listings.updated_at >= ?', Date.current - 30.day).
                order("random()").group('users.id').limit(12).each do |user| %>
        <div class="col-md-2 col-sm-3 col-xs-6 images">
        <div class="thumbnail images">
          <%= link_to image_tag(user.profileimage.url(:profile), class: "img-responsive dthumbnail"), vendor_path(user) %>
          <div class="caption dcaption">
            <h3><%= user.name.downcase.titleize %></h3>
           <div class="dtext line-clamp"><%= user.profilestory %></div>
          </div>
          <%= link_to "View Collection", vendor_path(id: user.id), class: "btn btn-xs btn-primary dbutton" %><br>
        </div>
     </div>
    <% end %>
  </div>
</div>



app/views/listings/_featured.html.erb
<h4>Customer Favorites</h4>

<div class="center">
  <div class="row">
    <% @listings.not_expired.where(:featured => true).order("random()").limit(12).each do |listing| %>
        <div class="col-md-2 col-sm-3 col-xs-6 images">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url(:medium), class: "img-responsive"), listing, data: { no_turbolink: true } %>
          <div class="caption">
            <h3><%= link_to listing.name.downcase.titleize, listing, data: { no_turbolink: true } %></h3>
            <p>
              <% if listing.saleprice.blank? %>
                <%= number_to_currency(listing.price) %>
              <% else %>
                <font color="red"><del><%= number_to_currency(listing.price) %></del>  
                <%= number_to_currency(listing.saleprice) %></font>
              <% end %>
            </p>
          </div>
        </div>
     </div>
    <% end %>
  </div>
</div>


app/views/listings/admin.html.erb

  <h3>Admin area: All Sellers - Non Expired Listings</h3>


<p><%= link_to "Download Listings (CSV)", listings_path(format: "csv"), class: "btn btn-xs btn-primary" %></p>
<p><%= will_paginate @listings, renderer: BootstrapPagination::Rails %></p>

<table class="table table-condensed">
  <tr>
    <th class="col-md-1">Featured</th>
    <th class="col-md-1">Image</th>
    <th class="col-md-1">Seller</th>
    <th class="col-md-2">Name</th>
    <th class="col-md-1">Price</th>
    <th class="col-md-1">Current Inventory</th>
    <th class="col-md-2">Date Listed</th>
    <th class="col-md-3">Action</th>
  </tr>

  <% @listings.each do |listing| %> 
    <tr>
      <td><%= best_in_place listing, :featured, :type => :checkbox, :collection => ["true", "false"] %></td>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.user_id %></td>
      <td><%= listing.name.downcase.titleize %></td>
      <td><% if listing.saleprice.blank? %>
          <%= number_to_currency(listing.price) %>
        <% else %>
          <del><%= number_to_currency(listing.price) %></del>  
          <%= number_to_currency(listing.saleprice) %>
        <% end %>
     </td>
      <td><%= listing.inventory %></td>
      <td><%= listing.created_at.strftime("%B %-d, %Y") %></td>

      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>
<p><%= will_paginate @listings, renderer: BootstrapPagination::Rails %></p>

app/views/listings/index.html.erb
<% provide(:title, "Boutique Jewelry and Accessories") %>
<% if params[:page].nil? %>

    <% if params[:sort].nil? %>
      <!--  <div class="well hpwell">
        <%= image_tag("mobile-logo.gif") %><br>Shop accessories from talented artisans and boutique brands.
        <br><span class="glyphicon glyphicon-chevron-down"></span>
       </div> -->

       <%= render 'featured' %>
       <!-- <%= render 'designers' %> -->
    <% end %>

<% end %>


<!-- <h4>Browse Collection</h4>

 <div class="dropdown">
    <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            Sort <%= params[:sort] %> <b class="caret"></b> </button>

    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to "New Arrivals", listings_path(:sort => "- New Arrivals")  %></li>
      <li><%= link_to "Price - Low to High", listings_path(:sort => "- Price - Low to High") %></li>
      <li><%= link_to "Price - High to Low", listings_path(:sort => "- Price - High to Low")  %></li>
      <li><%= link_to "Discover - Random Shuffle", listings_path(:sort => "- Random Shuffle")  %></li>
    </ul>

</div>
  <br>


<div class="center">

<% cache "homepage_p#{params[:page]}_s_#{params[:sort]}", skip_digest: true, expires_in: 1.days do %>
  <div class="row">
    <% @listings.not_expired.each do |listing| %>
      <div class="col-md-2 col-sm-3 col-xs-6 images">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url(:medium), class: "img-responsive"), listing, data: { no_turbolink: true } %>
          <div class="caption">
            <h3><%= link_to listing.name.downcase.titleize, listing, data: { no_turbolink: true } %></h3>
            <p>      
              <% if listing.saleprice.blank? %>
                <%= number_to_currency(listing.price) %>
              <% else %>
                <font color="red"><del><%= number_to_currency(listing.price) %></del>  
                <%= number_to_currency(listing.saleprice) %></font>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %> <!-- end cache block--> 

<!--  <p><%= will_paginate @listings, renderer: BootstrapPagination::Rails %></p>
</div> -->

<div class="center">
      <div class="row">
        <div class="col-md-3"><h4><%= link_to category_path(category: "Necklaces"), data: { no_turbolink: true } do %>Shop Necklaces    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
        <div class="col-md-3"><h4><%= link_to category_path(category: "Earrings"), data: { no_turbolink: true } do %>Shop Earrings    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
        <div class="col-md-3"><h4><%= link_to category_path(category: "Bracelets"), data: { no_turbolink: true } do %>Shop Bracelets    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
        <div class="col-md-3"><h4><%= link_to category_path(category: "Belts"), data: { no_turbolink: true } do %>Shop Belts    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
      </div>
    </div>

     <br>

<script>mixpanel.track("Homepage views")</script>

app/views/listings/new.html.erb
<div class="well">
    <font color="Red"><span class="glyphicon glyphicon-ok"></span> <b>Important:</b></font> Before listing items, please fill out your <b><%= link_to "bank account information", edit_user_url(current_user) %></b> so we can transfer your payments. Optional: fill out your <%= link_to "seller profile", sellerp_path(id: current_user.id) %> to tell customers about your brand and story. Your profile will show up in your product pages.
</div>

<h3>Option 1: Import a CSV File</h3>
<div class="well">
<font color="green"> <b>Import Instructions: </b></font>If you opt to use the import option, please read the <b><%= link_to 'Import Instructions', pages_csvimport_path %></b>. Once you prepare your file, try uploading a file with 2-3 products to test it out. If your listings load correctly, you can upload your full product file.
</div>

  <%= form_tag import_listings_path, multipart: true do %>
    <div class="row">
      <div class = "col-md-4">
        <div class="form-group"> <%= file_field_tag :my_file, :accept => "text/csv", class:"form-control" %> </div>
        <%= hidden_field_tag :user_id, current_user.id %>
      </div>
      <div class = "col-md-3">
          <div class="form-group"> <%= submit_tag "Import CSV", class:"btn btn-primary" %> </div> 
      </div>
    </div>
  <% end %>
  
<h3>Option 2: List New Items Manually</h3>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/listings/ownsearch.html.erb
<h3>Manage your Listings</h3>

<% if user_signed_in? %>
  <p>
    <%= link_to "Download Listings (CSV)", seller_path(format: "csv"), class: "btn btn-xs btn-primary" %> <%= link_to 'Add New Listings', new_listing_path, data: { no_turbolink: true }, class: "btn btn-xs btn-primary" %> <%= link_to 'Delete All Listings', delete_all_listings_path, method: :get, data: { confirm: "Are you sure you want to delete all your listings?" }, class: "btn btn-xs btn-danger" %>
  </p>

  <!-- SEARCH BOX -->
          <%= form_tag(ownsearch_listings_path, :method => "get", id: "search-form", class:"navbar-form navbar-right") do %>
            <div class="input-group"><%= text_field_tag :search, params[:search], placeholder: "Search by title...", class:"form-control search-form col-md-6 col-sm-12" %>
            <span class="input-group-btn"><button type="submit" class="btn btn-default btn-md"><span class="glyphicon glyphicon-search"></span></button></span></div>
              <% end %> 
    <br>
        <!-- END SEARCH BOX --> 
  
<% end %>
<table class="table table-condensed">
  <tr>
    <th class="col-md-2">Image</th>
    <th class="col-md-2">Name</th>
    <th class="col-md-2">Price</th>
    <th class="col-md-2">Current Inventory</th>
    <th class="col-md-2">Date Listed</th>
    <th class="col-md-2"></th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to image_tag(listing.image.url(:thumb)), listing, data: { no_turbolink: true } %></td>
      <td><%= link_to listing.name.downcase.titleize, listing, data: { no_turbolink: true } %></td>
      <td>    <% if listing.saleprice.blank? %>
                <%= number_to_currency(listing.price) %>
              <% else %>
                <del><%= number_to_currency(listing.price) %></del>  
                <%= number_to_currency(listing.saleprice) %>
              <% end %>
     </td>
      <td><%= listing.inventory %></td>
      <td><%= listing.created_at.strftime("%B %-d, %Y") %></td>
      <td>
<!--         <div class="btn-group">
          <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu"> -->
            <%= link_to "View", listing %><br>
            <%= link_to "Edit", edit_listing_path(listing) %><br>
            <%= link_to 'Delete', listing, method: :delete, data: { confirm: "Are you sure you want to delete this listing?" } %>
<!--           </ul>
        </div> -->
      </td>
    </tr>
  <% end %>
</table>

  <% if @listings.count == 0 %>
    <h5><font color="red">Your search term did not match any listings.</font></h5>
  <% end %>

app/views/listings/sale.html.erb
<h4><b>Sale!</b></h4>

 <div class="dropdown">
    <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            Sort <%= params[:sort] %> <b class="caret"></b> </button>

    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to "New Arrivals", sale_path(:sort => "- New Arrivals")  %></li>
      <li><%= link_to "Price - Low to High", sale_path(:sort => "- Price - Low to High") %></li>
      <li><%= link_to "Price - High to Low", sale_path(:sort => "- Price - High to Low")  %></li>
      <li><%= link_to "Discover - Random Shuffle", sale_path(:sort => "- Random Shuffle")  %></li>
    </ul>

</div>
  <br>

<div class="center">
  <div class="row">
    <% @listings.not_expired.each do |listing| %>
        <div class="col-md-2 col-sm-3 col-xs-6 images">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url(:medium), class: "img-responsive"), listing, data: { no_turbolink: true } %>
          <div class="caption">
            <h3><%= link_to listing.name.downcase.titleize, listing, data: { no_turbolink: true } %></h3>
            <p>      
              <% if listing.saleprice.blank? %>
                <%= number_to_currency(listing.price) %>
              <% else %>
                <font color="red"><del><%= number_to_currency(listing.price) %></del>  
                <%= number_to_currency(listing.saleprice) %></font>
              <% end %>
            </p>
          </div>
        </div>
     </div>
    <% end %>
  </div>
  <p><%= will_paginate @listings, renderer: BootstrapPagination::Rails %></p>
</div>
<br>

<script>mixpanel.track("Sale Category views")</script>

app/views/listings/seller.html.erb
<script>
  function refreshText() {
      $.ajax({
          url: '<%= check_listing_status_url %>',
          success: function (status) {
              if (status != -1) {
                  if (status == 0 || status == 1) {
                      setTimeout(refreshText, 5000);
                      show_info("Your listings are being imported. Depending on the number of listings in your file, this may take a few minutes to an hour. Please come back to this page to check if your import completed.");
                  } else if (status == 2) {
                      location.reload();
                  } else if (status == 3) {
                      show_error('Oops! We ran into an error. <br><br>Please refresh this page to check if some of your listings have loaded. If none of your listings loaded, check if your column names are as specified and check if you have all the required columns in the file. If some of your listings have loaded, then it means that the next listing in the file did not load because of an error in that row. <br><br>Please check the format of your listings at this link...and reload your file. After you make changes, you can upload your entire file again. Listings will not be duplicated.<br><br>If you need help, please review the <b><%= link_to 'Import Instructions', pages_csvimport_path %></b> again or send us your file to <b>service@outfitadditions.com</b>.');
                  }

              }
          }
      });
  }
  refreshText();

  function show_info(msg) {
      $("#ajax_message").addClass('alert').addClass('alert-warning');
      $("#ajax_message").text(msg);
  }

  function show_error(msg) {
      $("#ajax_message").addClass('alert').addClass('alert-danger').addClass("alert-dismissible");
      var message = $("#ajax_message");
      var closeBut = $('<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>');
      message.html(msg);
      message.append(closeBut);
  }
</script>

  <h3>Manage your Listings</h3>

<div id="ajax_message"></div>

<% if user_signed_in? %>
  <p>
    <%= link_to "Download Listings (CSV)", seller_path(format: "csv"), class: "btn btn-xs btn-primary" %> <%= link_to 'Add New Listings', new_listing_path, data: { no_turbolink: true }, class: "btn btn-xs btn-primary" %> <%= link_to 'Delete All Listings', delete_all_listings_path, method: :get, data: { confirm: "Are you sure you want to delete all your listings?" }, class: "btn btn-xs btn-danger" %>
  </p>
  
  <!-- pagitnation code here -->

  <!-- SEARCH BOX -->
           <%= form_tag(ownsearch_listings_path, :method => "get", id: "search-form", class:"navbar-form navbar-right") do %>
            <div class="input-group"><%= text_field_tag :search, params[:search], placeholder: "Search by title...", class:"form-control search-form col-md-6 col-sm-12" %>
            <span class="input-group-btn"><button type="submit" class="btn btn-default btn-md"><span class="glyphicon glyphicon-search"></span></button></span></div>
              <% end %> 
    <br>
        <!-- END SEARCH BOX --> 
  
<% end %>
<table class="table table-condensed">
  <tr>
    <th class="col-md-2">Image</th>
    <th class="col-md-2">Name</th>
    <th class="col-md-2">Price</th>
    <th class="col-md-2">Current Inventory</th>
    <th class="col-md-2">Date Listed</th>
    <th class="col-md-2"></th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to image_tag(listing.image.url(:thumb)), listing, data: { no_turbolink: true } %></td>
      <td><%= link_to listing.name.downcase.titleize, listing, data: { no_turbolink: true } %></td>
      <td>    <% if listing.saleprice.blank? %>
                <%= number_to_currency(listing.price) %>
              <% else %>
                <del><%= number_to_currency(listing.price) %></del>  
                <%= number_to_currency(listing.saleprice) %>
              <% end %>
     </td>
      <td><%= listing.inventory %></td>
      <td><%= listing.created_at.strftime("%B %-d, %Y") %></td>
      <td>
<!--         <div class="btn-group">
          <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu"> -->
            <%= link_to "View", listing %><br>
            <%= link_to "Edit", edit_listing_path(listing) %><br>
            <%= link_to 'Delete', listing, method: :delete, data: { confirm: "Are you sure you want to delete this listing?" } %>
<!--           </ul>
        </div> -->
      </td>
    </tr>
  <% end %>
</table>
<!-- pagination code here -->

  <% if @listings.count == 0 %>
    <h5><font color="red">You do not have any active listings at this time.</font></h5>
  <% end %>