config/routes.rb
Mktdemo::Application.routes.draw do
  

  devise_for :users

  resources :users, only: [:update, :edit]

  get '/seller/:id/profile' => "users#sellerp", as: :sellerp
  put '/seller/:id' => "users#sellerprofile", as: :sellerprofile

  resources :listings do
        collection do
          post 'import'
          get 'search'
          get 'ownsearch'
          get 'delete_all'
        end
   resources :orders, only: [:new, :create, :update, :show]
  end
 
  match "/swh", :to => "orders#swh", :as => :swh, :via => :post

  get '/listings/s/:id' => 'listings#vendor', as: 'vendor'
  get '/listings/c/:category' => 'listings#category', as: 'category'
  get '/listings/p/sale' => 'listings#sale', as:'sale'

  get "pages/about"
  get "pages/contact"
  get "pages/terms_conditions"
  get "pages/privacy_policy"
  get "pages/blogger_partnerships"
  get "pages/sell"
  get "pages/sellerfaqs"
  get "pages/csvimport"
  get "pages/returns"
  get "pages/feedback"
  get "pages/testpic"

  get 'seller' => "listings#seller"
  get 'check_listing_status' => "listings#check_listing_status"
  get 'sales' => "orders#sales"
  get 'shipconf' => "orders#shipconf"
  get 'purchases' => "orders#purchases"
  get 'thankyou' => "orders#thankyou"
  get 'admin' => "listings#admin"
  

  root 'listings#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :name, presence: true, uniqueness: true
   validates :profilestory, length: { in: 250..1500 }, if: "!profilestory.blank?"
   validates :tweet, length: { in: 20..140 }, if: "!tweet.blank?"
   validates_with AttachmentSizeValidator, :attributes => :profileimage, :less_than => 2.megabytes

   has_many :listings, dependent: :destroy
   has_many :orders, class_name: "Order", foreign_key: "seller_id"
   has_many :purchases, class_name: "Order", foreign_key: "buyer_id"


	if Rails.env.development?
		has_attached_file :profileimage, 
						  :styles => { :profile => "250x250", :p_thumb => "105x105" },
						  :default_url => "",
						  :convert_options => {:profile => '-background white -gravity center -extent 250x250',
						                       :p_thumb => '-background white -gravity center -extent 105x105' }
        validates_attachment_content_type :profileimage, :content_type => /\Aimage\/.*\Z/                                   
	else
		has_attached_file :profileimage, 
						  :styles => { :profile => "250x250", :p_thumb => "100x100" }, 
						  :default_url => "",
						  :convert_options => {:profile => '-background white -gravity center -extent 250x250',
						                       :p_thumb => '-background white -gravity center -extent 100x100' }
					      # :storage => :dropbox,
	    				  # :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
	    				  # :path => ":style/:id_:filename" 
	    validates_attachment_content_type :profileimage, :content_type => /\Aimage\/.*\Z/
	         
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :load_user
  before_filter :check_user, only: [:edit, :update, :sellerprofile, :sellerp]

def update
    @user.attributes = user_params
    Stripe.api_key = ENV["STRIPE_API_KEY"]
      token = params[:stripeToken]

      recipient = Stripe::Recipient.create(
        :name => user_params["bankaccname"], #if i want to save to db, use this: @user.bankaccname. not saving it                 
        :type => "individual",              #gives you only one set of error messages. i don't need the respond
        :bank_account => token              #to block either i think. eg. when i enter firstname only, i get two error
        )                                   #msgs

      @user.recipient = recipient.id

     respond_to do |format|
      if @user.save
        format.html { redirect_to edit_user_url, notice: 'Your account was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def sellerp
  end

  def sellerprofile
     respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to sellerp_url, notice: 'Your profile was successfully updated.' }
      else
        format.html { render action: 'sellerp' }
      end
    end
    ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)

  end
  

  private

  def load_user
    @user = User.find(params[:id])
  end

    def check_user
      if current_user != User.find(params[:id])
        redirect_to root_url, alert: "Sorry, please sign in to access this page. 
                                     #{ActionController::Base.helpers.link_to "Login", new_user_session_path}".html_safe
      end
    end

  def user_params
    params.require(:user).permit(:bankaccname, :profileimage, :profilestory, :tweet, :hidelistings, :sellershare)
  end
end

app/views/users/edit.html.erb
<h3>Secure Form - Edit Bank Account Details</h3>
<p><font color="red"><b>Currently transferring payments to US Accounts only.</b></font></p>

  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this update from being saved:</h4>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
      <noscript>JavaScript is not enabled and is required for this form. Please enable it in your web browser settings.</noscript>
  </div>

  <div class="alert alert-warning" >
  <p>
    <b>Current Account Details Saved:</b><br>
    <% if @user.recipient.present? %>

          <% require "stripe" 
              Stripe.api_key = ENV["STRIPE_API_KEY"] 
              rp = Stripe::Recipient.retrieve(@user.recipient)
          %>

        <%=  "Name on Account: #{rp.name}"  %><br>
        <%=  "Bank Name: #{rp.active_account.bank_name}"  %><br>
        <%=  "Last 4 of Account number: **** #{rp.active_account.last4}"  %><br>
    <% else %>
        You currently do not have any account details saved. Please fill out the form below and your account details will be displayed here as confirmation. You may change your account details at any time.
    <% end %>
  </p><br>
  <p><font size="2px"><span class="glyphicon glyphicon-lock"></span> Secure payments & transfers. Powered by <a href="http://www.stripe.com" target=blank>Stripe.com.</a></font></p>
  <p><a href="http://www.stripe.com" target=blank><%= image_tag("stripe.png") %></a></p>
  </div>
  

  
  

<%= form_for @user, url: user_path, html: { :class => 'bankinfo', method: :put } do |f| %>
	 <div class="form-group">
	  <%= f.label :full_name_as_it_appears_in_your_bank_account %>
	  <%= f.text_field :bankaccname, class:"form-control" %>
	 </div>

     <div class="form-group">
      <%= label_tag :country, "Country Code (must enter 'US' here. Only accepting US accounts at this time.)" %>
      <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
    </div> 
    <div class="form-group">
      <%= label_tag :routing_number %>
      <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :account_number %>
      <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
    </div>

    <p><font color="green"><b>When your products sell, funds will be direct deposited into your bank account within 2-3 business days.</b></font></p>

	 <div class="form-group">
	    <%= f.submit "Update Payment Details", class:"btn btn-primary" %> 
	 </div>

<% end %>

app/views/users/sellerp.html.erb
<h3> Seller Profile (optional) </h3>

  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this update from being saved:</h4>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="well"><p><font color="green"><b>Tell customers your story: </b></font> If you're a designer, tell customers your approach to design and your background. If you're a boutique, talk about your collection and the types of designers you work with.</p>
<p><font color="green"><span class="glyphicon glyphicon-ok"></span></font> Your profile info will be displayed on all your product pages. </p></div>

<%= form_for @user, url: sellerprofile_path(id: current_user.id), method: :put, html: { :class => 'edit_profile', :multipart => true } do |f| %>

  <div class="form-group">
    <%= f.label :tweet, "Describe your collection in a tweet." %> (140 characters or less)
    <%= f.text_field :tweet, class:"form-control", :rows => 5 %>
  </div>
       <% if !@user.tweet.blank? %>
          <i>Current:</i> <%= @user.tweet %>
      <% end %>
   <% if !@user.tweet.blank? %><br><br><% end %>
  <div class="form-group">
    <%= f.label :profilestory, "Your story: Give customers some background on your brand and style." %> (between 250-1500 characters)
    <%= f.text_area :profilestory, class:"form-control", :rows => 5 %>
  </div>
         <% if !@user.profilestory.blank? %>
          <i>Current profile:</i> <%= @user.profilestory %>
      <% end %>
   <% if !@user.profilestory.blank? %><br><br><% end %>

  <div class="form-group">
    <%= f.label :profile_image %> (profile pic of the designer or a logo.)
    <%= f.file_field :profileimage, class:"form-control" %>
  </div>
       <% if !@user.profileimage.url.blank? %>
          <i>Current image:</i> <%= image_tag(@user.profileimage.url(:p_thumb)) %>
      <% end %>
    <% if !@user.profileimage.url.blank? %><br><br><% end %>

         <p>
            <%= f.check_box :hidelistings, :collection => ["true", "false"] %>
            <%= f.label :hidelistings, "Hide Listings" %> (Checking this box will take your listings off our site. To activate listings, please uncheck this box.)
        </p>

   <div class="form-group">
        <%= f.submit "Update", class:"btn btn-primary" %>
   </div>

 <% end %>