config/routes.rb
Mktdemo::Application.routes.draw do
  

  devise_for :users

  resources :users, only: [:update, :edit]

  get '/seller/:id/profile' => "users#sellerp", as: :sellerp
  put '/seller/:id' => "users#sellerprofile", as: :sellerprofile

  resources :listings do
        collection do
          post 'import'
          get 'search'
          get 'ownsearch'
          get 'delete_all'
        end
   resources :orders, only: [:new, :create, :update, :show]
  end
 
  match "/swh", :to => "orders#swh", :as => :swh, :via => :post

  get '/listings/s/:id' => 'listings#vendor', as: 'vendor'
  get '/listings/c/:category' => 'listings#category', as: 'category'
  get '/listings/p/sale' => 'listings#sale', as:'sale'

  get "pages/about"
  get "pages/contact"
  get "pages/terms_conditions"
  get "pages/privacy_policy"
  get "pages/blogger_partnerships"
  get "pages/sell"
  get "pages/sellerfaqs"
  get "pages/csvimport"
  get "pages/returns"
  get "pages/feedback"
  get "pages/testpic"

  get 'seller' => "listings#seller"
  get 'check_listing_status' => "listings#check_listing_status"
  get 'sales' => "orders#sales"
  get 'shipconf' => "orders#shipconf"
  get 'purchases' => "orders#purchases"
  get 'thankyou' => "orders#thankyou"
  get 'admin' => "listings#admin"
  

  root 'listings#index'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :cardname, :address, :city, :state, :zip, 
	          :shipname, :shipaddress, :shipcity, :shipstate, :shipzip, 
	          :tracking, :carrier, presence: true
	validates :zip, :shipzip, length: { is: 5 }

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"

    after_create :decrement_stock

	def decrement_stock
	    self.listing.update_attribute("inventory", (listing.inventory - 1))
	end

def self.to_csv(orders)
 wanted_columns = [:id, :shipname, :created_at, :shipcompany, :shipaddress, :shipaddress2, :shipcity, :shipstate, :shipzip]
  CSV.generate do |csv|
    csv << wanted_columns + [:item_name, :price, :saleprice] 
    orders.each do |order|
	    attr = order.attributes.with_indifferent_access.values_at(*wanted_columns)
	    attr.push(order.listing.name, order.listing.price, order.listing.saleprice)
	    csv << attr
   end
  end
 end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:swh]
  before_action :check_user, only: [:edit, :update, :show]
  before_action :check_buyer, only: [:thankyou]
  # before_filter :set_cache_buster

  # def set_cache_buster
  #   response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
  #   response.headers["Pragma"] = "no-cache"
  #   response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  # end
 
  
  # GET /orders
  # GET /orders.json

  def sales
    @orders = Order.where(seller: current_user).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
         respond_to do |format|
         format.html
         format.csv { send_data @orders.to_csv(@orders) }  
      end
  end

  def purchases
    @orders = Order.where(buyer: current_user).order("created_at DESC").paginate(:page => params[:page], :per_page => 48)
  end

  def show
  end


    # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.friendly.find(params[:listing_id])
  end


   # POST /orders
  # POST /orders.json
def create
  @order = Order.new(order_params)
  charge_error = nil

    @listing = Listing.friendly.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.listingsku = @listing.sku
    @order.listingimage = @listing.image.url(:thumb)
    @order.listingname = @listing.name
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

  if @order.valid?
    if @listing.saleprice.blank? #price
        @order.price_sold = @listing.price
        @order.seller_payment = (((@listing.price * 97.1) - 30) * (@seller.sellershare * 0.0001)) #.008 to convert back to dollars

        begin
          charge = Stripe::Charge.create(
            :amount => (@listing.price * 100).floor,
            :currency => "usd",
            :card => token,
            :description => "Charge from OutfitAdditions"
            )

        rescue Stripe::CardError => e
          charge_error = e.message
        end
        if charge_error
          flash[:error] = charge_error
          render :new
        else
          @order.save
          redirect_to thankyou_path(:id => @order.id)
          AutoNotifier.orderconf_email(current_user, @order).deliver 
          AutoNotifier.sellerconf_email(current_user, @seller, @order).deliver 
               if !@seller.recipient.blank? and @seller.name != "Outfit Additions"
                   transfer = Stripe::Transfer.create(
                  :amount => (((@listing.price * 97.1) - 30) * (@seller.sellershare * 0.01)).floor, # 0.8 to convert to cents per stripe requirement. 80 percent in cents goes to seller.
                  :currency => "usd",
                  :recipient => @seller.recipient,
                  :description => "Transfer from OutfitAdditions"
                  )
               end #end transfer if saleprice is blank
        end 
    else #saleprice
        @order.price_sold = @listing.saleprice
        @order.seller_payment = (((@listing.saleprice * 97.1) - 30) * (@seller.sellershare * 0.0001)) #.008 to convert back to dollars

        begin
          charge = Stripe::Charge.create(
            :amount => (@listing.saleprice * 100).floor,
            :currency => "usd",
            :card => token,
            :description => "Charge from OutfitAdditions"
            )

        rescue Stripe::CardError => e
          charge_error = e.message
        end
        if charge_error
          flash[:error] = charge_error
          render :new
        else
          @order.save
          redirect_to thankyou_path(:id => @order.id)
          AutoNotifier.orderconf_email(current_user, @order).deliver 
          AutoNotifier.sellerconf_email(current_user, @seller, @order).deliver 
               if !@seller.recipient.blank? and @seller.name != "Outfit Additions"
                   transfer = Stripe::Transfer.create(
                  :amount => (((@listing.saleprice * 97.1) - 30) * (@seller.sellershare * 0.01)).floor, #0.8 to convert to cents per stripe requirement. 80 percent in cents goes to seller.
                  :currency => "usd",
                  :recipient => @seller.recipient,
                  :description => "Transfer from OutfitAdditions"
                  )
               end #end transfer if saleprice is blank
        end
    end #if @listing.saleprice.blank
  else
          render :new
  end # end order.valid

  ActionController::Base.new.expire_fragment("homepage_p#{params[:page]}_s_#{params[:sort]}", options = nil)
end # end create

  def swh
  end

  def thankyou
    @order = Order.find(params[:id])
  end

  def shipconf
      @order = Order.find(params[:id])
      AutoNotifier.shipconf_email(@order).deliver
      #We send an email, so you cannot send another one for this order
      @order.mail_status = true
      @order.save!
  end

  def update
    respond_to do |format|
    if @order.update(order_params)
      format.html { redirect_to(sales_url, :notice => 'Order was successfully updated.') }
      format.json { respond_with_bip(@order) }
    else
      format.html { render :action => "edit" }
      format.json { respond_with_bip(@order) }
    end
  end
end
   

private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:shipname, :shipcompany,:shipaddress, :shipaddress2, :shipcity, :shipstate, 
                                    :shipzip, :cardname, :address, :address2, :city, :state, :zip, :comments,
                                     :tracking, :carrier, :emailsub, :listingimage, :listingname, :listingsku)
    end

    def check_user
      if current_user.id != @order.seller_id && current_user.name != "admin admin"
        redirect_to root_url, alert: "Sorry, you are not authorized to view this page because you are not the seller of this listing."
      end
    end

    def check_buyer
      @order = Order.find(params[:id])
      if current_user.id != @order.buyer_id
        redirect_to root_url, alert: "Sorry, you are not authorized to view that order."
      end
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <h3><%= @listing.name %></h3>
    <h4>
      <% if @listing.saleprice.blank? %>
         <%= number_to_currency(@listing.price) %>
      <% else %>
        <del><%= number_to_currency(@listing.price) %></del>  
          <%= number_to_currency(@listing.saleprice) %>
      <% end %>
    </h4>
    <div class="thumbnail orderthumb">
      <%= image_tag @listing.image.url %>
    </div>
  </div>
  <div class="col-md-8">

<%= form_for([@listing, @order]) do |f| %>

  <h3>Place Order</h3>

  <p><b><font color="green">Order Total: 
           <% if @listing.saleprice.blank? %>
            <%= number_to_currency(@listing.price) %>
           <% else %>
             <%= number_to_currency(@listing.saleprice) %>
           <% end %>
         </font></b></p>

  <!-- <p><font color="red" size="3px">Shipping Delay: We are on vacation. Your order will ship on 1/20. </font></p> -->

  <h4><b>Shipping Details</b></h4>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :shipname, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :company %> (optional)
    <%= f.text_field :shipcompany, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :shipaddress, "Shipping Address" %> (line 1)
    <%= f.text_field :shipaddress, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :shipaddress2, "Shipping Address" %> (line 2)
    <%= f.text_field :shipaddress2, class:"form-control" %>
  </div>
<div class="row">
  <div class = "col-md-4">
      <div class="form-group">
        <%= f.label :shipcity, "Shipping City" %>
        <%= f.text_field :shipcity, class:"form-control" %>
      </div>
  </div>
  <div class = "col-md-4">
    <div class="form-group">
        <%= f.label :shipstate, "Shipping State" %>
        <%= f.select(:shipstate, options_for_select(us_states, f.object.shipstate), {prompt: "Select"}, {class: "form-control"}) %>
    </div>  
  </div>
  <div class = "col-md-4">
      <div class="form-group">
        <%= f.label :shipzip, "Shipping Zip (5-digit)" %>
        <%= f.text_field :shipzip, class:"form-control" %>
      </div>
  </div>
</div>
  <h4><b>Billing Details</b></h4>
  <div class="form-group">
    <%= f.label :cardname, "Full Name (as printed on credit card)" %>
    <%= f.text_field :cardname, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address, "Billing Address" %> (line 1)
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address2, "Billing Address" %> (line 2)
    <%= f.text_field :address2, class:"form-control" %>
  </div>

<div class="row">
  <div class = "col-md-4">
      <div class="form-group">
        <%= f.label :city, "Billing City" %>
        <%= f.text_field :city, class:"form-control" %>
      </div>
  </div>
  <div class = "col-md-4">
      <div class="form-group">
        <%= f.label :state, "Billing State" %>
        <%= f.select(:state, options_for_select(us_states, f.object.state), {prompt: "Select"}, {class: "form-control"}) %>
      </div>
  </div>
  <div class = "col-md-4">
      <div class="form-group">
        <%= f.label :zip, "Billing Zip (5-digit)" %>
        <%= f.text_field :zip, class: "form-control" %>
      </div>
  </div>
</div>

      <div class="form-group">
        <%= f.label :Order_Comments %> (if any)
        <%= f.text_area :comments, class:"form-control" %>
      </div>

  <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
        <br>
        <p>
            <%= f.check_box :emailsub, :collection => ["true", "false"], :checked => true %> Sign up for email - deals, new arrivals, contests & more.
        </p>

        <p><b><font color="green">You will be charged: 
           <% if @listing.saleprice.blank? %>
            <%= number_to_currency(@listing.price) %>
           <% else %>
             <%= number_to_currency(@listing.saleprice) %>
           <% end %>
        </font></b></p>

      </div>

  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. Please enable it in your web browser settings.</noscript>
  </div>

  <div class="actions">
    <%= f.submit "Pay for Order", class:"btn btn-success" %>
  </div>

<% end %>

<br>
<%= link_to 'Back to listing', listing_path(@listing) %>
<p>
</div>

app/views/orders/new.html.erb
<!--<h1>Order for <%= @listing.name %></h1> -->
<%= render 'form' %>

</div>

<script>mixpanel.track("Order form views")</script>

app/views/orders/purchases.html.erb

  <h3>Purchase History for <%= current_user.name %></h3>


<table class="table table-condensed">
  <tr>
    <th class="col-md-2">Image</th>
    <th class="col-md-2">Item</th>
    <th class="col-md-1">Price paid</th>
    <th class="col-md-2">Seller</th>
    <th class="col-md-2">Date Purchased</th>
    <th class="col-md-1"><font color="green">Carrier</font></th>
    <th class="col-md-2"><font color="green">Shipment Tracking #</font</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= link_to image_tag(order.listingimage), order.listing, data: { no_turbolink: true } %></td>
      <td><%= link_to order.listingname, order.listing, data: { no_turbolink: true } %></td>
      <td><%= number_to_currency(order.price_sold) %></td>
      <td><%= order.seller.name %></td>
      <td><%= order.created_at.strftime("%B %-d, %Y") %></td>
      <td><font color="green"><%= order.carrier %></font</td>
      <td><font color="green"><%= order.tracking %></font</td>
    </tr>
  <% end %>
</table>
<div class="center"><p><%= will_paginate @listings, renderer: BootstrapPagination::Rails %></p></div>

  <% if @orders.count == 0 %>
    <h5><font color="red">You do not have any past orders with us.</font></h5>
  <% end %>

app/views/orders/sales.html.erb
 <h3>Sales History for <%= current_user.name %></h3>

<% if user_signed_in? %>
  <p><%= link_to "Download orders (CSV)", sales_path(format: "csv"), class: "btn btn-xs btn-primary" %></p>
<% end %>
<table class="table table-condensed table-responsive">
  <tr>
    <th class="col-md-1">Order ID</th>
    <th class="col-md-1">Date Sold</th>
    <th class="col-md-1">Image</th>
    <th class="col-md-1">Item</th>
    <th class="col-md-1">Price Sold</th>
    <th class="col-md-1">Seller Payment (after fees)</th>
    <th class="col-md-2">Shipping Details</th>
    <th class="col-md-1">Carrier (click below to enter)</th>
    <th class="col-md-2">Tracking # (click below to enter)</th>
    <th class="col-md-1">Ship Order</th>
  </tr>

  <% @orders.each do |order| %> 
    <tr>
      <td><%= order.id %></td>
      <td><%= order.created_at.strftime("%B %-d, %Y") %></td>
      <td><%= link_to image_tag(order.listingimage), order.listing, data: { no_turbolink: true } %></td>
      <td><%= link_to order.listingname, order.listing, data: { no_turbolink: true } %></td>
      <td><%= number_to_currency(order.price_sold) %></td>
      <td><%= number_to_currency(order.seller_payment)  %></td>
      <td><%= order.shipname %><br>
          <%= if !order.shipcompany.blank? then order.shipcompany end %><% if !order.shipcompany.blank? %><br><% end %>
          <%= order.shipaddress %><br>
          <%= if !order.shipaddress2.blank? then order.shipaddress2 end %><% if !order.shipaddress2.blank? %><br><% end %>
          <%= "#{order.shipcity}, #{order.shipstate} #{order.shipzip}" %>
      </td>
      <td><%= best_in_place order, :carrier, :type => :input, :url => listing_order_path(id: order.id, listing_id: order.listing_id), class: "tracking" %> </td>
      <td><%= best_in_place order, :tracking, :type => :input, :url => listing_order_path(id: order.id, listing_id: order.listing_id), class: "tracking" %> </td>
      <td><p><%= link_to "Get Invoice", listing_order_path(id: order.id, listing_id: order.listing_id), class: "btn btn-xs btn-success shipconf" %></p><%= link_to order.mail_status ? "Shipment Confirmed":"Confirm Shipment", shipconf_path(id: order.id), class: "btn btn-xs btn-success shipconf", disabled:order.mail_status %></td>
    </tr>
  <% end %>
</table>

<div class="center"><p><%= will_paginate @listings, renderer: BootstrapPagination::Rails %></p></div>

  <% if @orders.count == 0 %>
    <h5><font color="red">You do not have any past sales.</font></h5>
  <% end %>

app/views/orders/shipconf.html.erb
<p>Thank you for confirming this shipment. Your customer has been sent a confirmation email. If you haven't already done so, please enter your tracking number and carrier name for your order in your sales page. </p>

<p><%= link_to "Go Back to Sales Page", sales_path, class: "btn btn-sm btn-primary" %></p>

app/views/orders/show.html.erb
      
      <br><br><br>
      <p><%= link_to 'Print Invoice', request.original_url, :onclick => 'window.print();return false;', class: "btn btn-sm btn-success pbtn"%></p>
       <br>
       <p><img src="https://s3.amazonaws.com/oamktplace/2014logo.jpg"></p> 

       <p>
         Dear <%= @order.cardname %>, <br><br>Thank you for your order at Outfit Additions. <br><br>
         <b>Order Number:</b> <%= @order.id %><br>
         <b>Order Date:</b> <%= @order.created_at.strftime("%B %-d, %Y") %><br>
         <b>Item ordered:</b> <%= @order.listing.name %><br>
         <b>Seller Name:</b> <%= @order.seller.name %><br>
         <b>Total charged:</b> <% if @order.listing.saleprice.blank? %><%= number_to_currency(@order.listing.price) %><% else %>
         <%= number_to_currency(@order.listing.saleprice) %><% end %>
       </p>

         <b>Billed to: </b><br>
           <%= @order.cardname %><br>
           <%= @order.address %><br>
           <%= if !@order.address2.blank? then @order.address2 end %><% if !@order.address2.blank? %><br><% end %>
           <%= "#{@order.city}, #{@order.state} #{@order.zip}" %><br>
           <% if !@order.comments.blank? %>
          <b>Comments:</b> <%= @order.comments %><br>
          <% end %>
          <br>
          <b>Shipped to: </b><br>
           <%= @order.shipname %><br>
           <%= if !@order.shipcompany.blank? then @order.shipcompany end %><% if !@order.shipcompany.blank? %><br><% end %>
           <%= @order.shipaddress %><br>
           <%= if !@order.shipaddress2.blank? then @order.shipaddress2 end %><% if !@order.shipaddress2.blank? %><br><% end %>
           <%= "#{@order.shipcity}, #{@order.shipstate} #{@order.shipzip}" %><br><br>

       <p>Returns are accepted if item is returned within 30 days of the order date. Please email service@outfitadditions.com for return instructions. </p>
       <p>--The Outfit Additions team</p>
       <br>
       <br>

app/views/orders/thankyou.html.erb
<% provide(:title, 'Order Confirmation') %>
<h3>Thank you for your order.</h3>
An email confirmation has been sent to you with your order details. <br>
You will recieve an email in 1-2 business days when your item ships. You may visit your <a href="http://www.outfitadditions.com/purchases">purchases</a> page at any time to view your order details.<br><br>
<b>Order Confirmation:</b><br>
 <div class = "row">
	<div class = "col-md-4">
		<%= "Order ID: #{@order.id}" %><br>
		<%= "Item: #{@order.listing.name.downcase.titleize}" %><br>
		<%= "Price: #{number_to_currency @order.price_sold}" %><br>
		<%= image_tag(@order.listing.image.url(:medium))  %><br><br>
	</div>
 </div>
 <br>

<!-- Avantlink tracking -->
<script type="text/javascript">
var _AvantMetrics = _AvantMetrics || [];
_AvantMetrics.push(['order',{ order_id:<%= @order.id %>, amount:<%= @order.price_sold %> }]);
</script>
<!-- End Avantlink tracking -->

<!-- Optimizely tracking -->
<script>
    window.optimizely = window.optimizely || [];
    window.optimizely.push(['trackEvent', 'order_confirmation', {'revenue': <%= @order.price_sold * 100 %>}]);
    window.optimizely.push(['trackEvent', 'orderNumber', {'orderNumber': <%= @order.id %>}]);
</script>
<!-- End Optimizely tracking -->

<!-- End Mixpanel tracking -->
<script>mixpanel.track("Order confirmation")</script>
<!-- End Mixpanel tracking -->

<!-- Facebook Conversion Code for Checkouts - OA -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6026896913946', {'value':<%= @order.price_sold %>,'currency':'USD'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6026896913946&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" /></noscript>

<!-- End Facebook tracking -->