config/routes.rb
Mktdemo::Application.routes.draw do
  

  devise_for :users

  resources :users, only: [:update, :edit]

  get '/seller/:id/profile' => "users#sellerp", as: :sellerp
  put '/seller/:id' => "users#sellerprofile", as: :sellerprofile

  resources :listings do
        collection do
          post 'import'
          get 'search'
          get 'ownsearch'
          get 'delete_all'
        end
   resources :orders, only: [:new, :create, :update, :show]
  end
 
  match "/swh", :to => "orders#swh", :as => :swh, :via => :post

  get '/listings/s/:id' => 'listings#vendor', as: 'vendor'
  get '/listings/c/:category' => 'listings#category', as: 'category'
  get '/listings/p/sale' => 'listings#sale', as:'sale'

  get "pages/about"
  get "pages/contact"
  get "pages/terms_conditions"
  get "pages/privacy_policy"
  get "pages/blogger_partnerships"
  get "pages/sell"
  get "pages/sellerfaqs"
  get "pages/csvimport"
  get "pages/returns"
  get "pages/feedback"
  get "pages/testpic"

  get 'seller' => "listings#seller"
  get 'check_listing_status' => "listings#check_listing_status"
  get 'sales' => "orders#sales"
  get 'shipconf' => "orders#shipconf"
  get 'purchases' => "orders#purchases"
  get 'thankyou' => "orders#thankyou"
  get 'admin' => "listings#admin"
  

  root 'listings#index'

  

end

app/views/layouts/_footer.html.erb
<footer>

	<div class="container">
       
		<div class="row">
			<div class="col-sm-5">
				<h6><b>About Us</b></h6>
				<p>Outfit Additions is a curated jewelry marketplace. We work hard to find exceptionally talented jewelry designers and boutique jewelry brands and make their lines available to buy. As part of our vetting process, we approve sellers based on the originality of their design, materials used and their attention to detail. We operate as a marketplace so sellers ship your order direct to you. <br><br>All US orders ship FREE + No hassle 30 day returns. We want you to be happy with your purchase.</p>
			</div><!-- end col -->
			
			<div class="col-sm-2">
				<h6>Learn More</h6>
				<ul class="unstyled">
				  <li><%= link_to "About", pages_about_path  %></li>
				  <li><%= link_to "Blogger Partnerships", pages_blogger_partnerships_path %></li>
				  <li><%= link_to "Terms & Conditions", pages_terms_conditions_path %></li>
				  <li><%= link_to "Privacy Policy", pages_privacy_policy_path %></li>
				  <li><%= link_to "Easy Returns", pages_returns_path %></li><br>
				  <li><%= link_to "Sell With Us", pages_sell_path, class: "btn btn-success btn-sm" %></li>
				</ul>
			</div><!-- end col -->
			
			<div class="col-sm-1">
				<h6>Connect</h6>
				<ul class="unstyled">
					<li><%= link_to "Contact Us", pages_contact_path %></li>
					<li><a href="http://blog.outfitadditions.com">Blog</a></li>
					<li><a href="https://www.facebook.com/pages/Outfit-Additions/129192821680">Facebook</a></li>
					<li><a href="http://www.pinterest.com/outfitadditions/">Pinterest</a></li>
				</ul>
			</div><!-- end col -->
			
			<div class="col-sm-4">
			  <ul class="unstyled">
			  	<li> <%= render 'mailchimp' %> </li>
			  </ul>
			</div><!-- end col -->
		</div><!-- end row -->
	</div><!-- end container -->
			<div class="center">Designed & Coded with <span class="glyphicon glyphicon-heart"></span> in San Francisco. | Copyright &copy; 2014 Outfit Additions | <span class="glyphicon glyphicon-lock"></span> Secure payments. Powered by <a href="http://www.stripe.com" target=blank>Stripe.com.</a></div>

   <!-- avantlink code -->
      <script src="https://s3.amazonaws.com/oamktplace/avmws_1012159.js" type="text/javascript"></script>
   <!-- avantlink code end -->

</footer>  


app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">OUTFIT ADDITIONS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <!-- ACCOUNT LINKS -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>     <%= current_user.name.titleize %> <span class="glyphicon glyphicon-chevron-down"></span></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                  <% if current_user.name == "admin admin" %>
                      <li><%= link_to "Admin", admin_path, data: { no_turbolink: true }  %></li>
                  <% end %>
                    <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
                    <li><%= link_to "Past Orders", purchases_path  %></li>
                  <% if Rails.env.development? or ["admin admin", "Outfit Additions", "Test8880"].include? current_user.name %>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation" class="dropdown-header"><b>Seller links</b></li>
                    <li><%= link_to "List Items to Sell", new_listing_path, data: { no_turbolink: true }  %></li>
                    <li><%= link_to "Manage Listings", seller_path  %></li>
                    <li><%= link_to "Payment Settings", edit_user_path(current_user), data: { no_turbolink: true }  %></li>
                    <li><%= link_to "Manage Sales", sales_path  %></li>
                    <li><%= link_to "Seller Profile", sellerp_path(current_user) %></li>
                    <li><%= link_to "Seller FAQ's", pages_sellerfaqs_path %></li>
                    <li><%= link_to "Feedback/Contact", pages_feedback_path %></li>
                  <% end %>
            </ul>            
          </li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path  %></li>
            <li><%= link_to "Login", new_user_session_path  %></li>
        <% end %>
      </ul>
  <!-- END ACCOUNT LINKS -->

          <!-- SEARCH BOX -->
           <%= form_tag(search_listings_path, :method => "get", id: "search-form", class:"navbar-form navbar-right") do %>
            <div class="input-group"><%= text_field_tag :search, params[:search], placeholder: "Search by color or style...", :size => "20", class:"form-control search-form" %>
            <span class="input-group-btn"><button type="submit" class="btn btn-default btn-md"><span class="glyphicon glyphicon-search"></span></button></span></div>
              <% end %> 

        <!-- END SEARCH BOX --> 

     <!-- CATEGORY DROP DOWN -->
       <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Category <span class="glyphicon glyphicon-chevron-down"></span></a>
           <ul class="dropdown-menu">
             <li><%- Listing.uniq.pluck(:category).each do |category| %>
               <%= link_to category, category_path(category: category) %> 
              <% end %>
             </li>
           </ul>
         </li>
        </ul>
   <!-- END CATEGORY DROP DOWN -->
    
   <!-- SALE LINK -->
       <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sale", sale_path, class: "salelink" %> </li>
       </ul>
       <!-- END SALE LINK -->


    </div><!-- /.navbar-collapse --> 
  </div><!-- /.container-fluid -->
</nav><!-- navbar end -->

<!-- error meessages -->
  <div class="container">
     <% unless current_page?(thankyou_path) %>
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <!-- error meessages end -->

<% if params[:page].nil? and params[:sort].nil? and current_page?(root_path) %>

 <div class="jumbotron hpwell">
  <div class="container">
        <%= image_tag("mobile80.gif") %><br>Shop accessories from talented artisans & boutique brands.
        <br><font color="orange">Free shipping. Easy Returns.</font>
        <br><span class="glyphicon glyphicon-chevron-down"></span>
            <div class="center">
              <div class="row">
                <div class="col-md-3 cbtn"><h4><%= link_to category_path(category: "Necklaces"), class: "clink", data: { no_turbolink: true } do %>Shop Necklaces    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
                <div class="col-md-3 cbtn"><h4><%= link_to category_path(category: "Earrings"), class: "clink", data: { no_turbolink: true } do %>Shop Earrings    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
                <div class="col-md-3 cbtn"><h4><%= link_to category_path(category: "Bracelets"), class: "clink", data: { no_turbolink: true } do %>Shop Bracelets    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
                <div class="col-md-3 cbtn"><h4><%= link_to category_path(category: "Belts"), class: "clink", data: { no_turbolink: true } do %>Shop Belts    <span class="glyphicon glyphicon-chevron-right"></span><% end %></h4></div>
              </div>
            </div>
  </div>
</div>


<!-- carousel 
   <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item">
          <%= image_tag("pablo1.png") %>
        </div>
        <div class="item active">
          <%= image_tag("pablo2.png") %>
        </div>        
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>  end carousel -->

<% end %>




 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="//cdn.optimizely.com/js/2798530582.js"></script>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>


 <% if current_page?(listings_path) %>
      <meta property="og:title" content= <%= @listing.name %> />
      <meta property="og:type" content="product" />
      <meta property="og:price:amount" content=<%= @listing.price %> />
      <meta property="og:price:currency" content="USD" />
  <% end %>

    <!-- this is for the royalslider plugin  -->
		 <style>
		      #gallery-1 {
		  width: 100%;
		  -webkit-user-select: none;
		  -moz-user-select: none;  
		  user-select: none;
		}

		    </style>   
    <!-- end code for royalslider plugin --> 

    <!-- sumome 
    <script src="//load.sumome.com/" data-sumo-site-id="69f99888544a936d93961dc09d5686eaa0bc06c2371a31ad43abb3c52028a7d2" async></script> 
     end code for sumome -->
</head>
<body>
   <% if Rails.env.production? %>  
        <%= render 'googletagmanager' %>
   <% end %>
	<%= render 'layouts/header' %>
	<div class="container">

   <!-- error msg code went here -->

		<%= yield %>
	
		<%= render 'layouts/footer' %>
	</div>
  <% if Rails.env.production? %>  
        <%= render 'googleremarketing' %>
   <% end %>
</body>
</html>